blog/blog/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('monitor/', include('monitor.urls')),
    path('admin/', admin.site.urls),
    
]

blog/monitor/urls.py
from django.urls import path
from django.conf.urls import  include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('details/', views.details, name='details'),
    path('datepickerview/', views.datepickerview, name='datepickerview'),
    
]

blog/monitor/models.py
from django.db import models
from itertools import groupby
 
class Messages(models.Model):
    channel_name = models.CharField(max_length=255, blank=True, null=True)
    channel_id = models.CharField(max_length=255, blank=True, null=True)
    message_id = models.IntegerField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    time = models.TimeField(blank=True, null=True)
    url = models.CharField(max_length=100, blank=True, null=True)
    views = models.IntegerField(blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    date_added = models.DateField(blank=True, null=True)
    time_added = models.TimeField(blank=True, null=True)
    pid_thread = models.CharField(db_column='PID_Thread', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'messages'
       
    def __str__(self):
        return '{},{},{},{}'.format(self.date,self.time,self.message,self.pid_thread)
    

blog/monitor/forms.py
from django import forms
from monitor.models import Messages
from datetime import date

class DateRangeForm(forms.ModelForm):
    #BIRTH_YEAR_CHOICES = ('2018','2017','2016')
    #name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    #name = forms.DateField(widget=forms.SelectDateWidget())
    day = date.today()
    date = forms.DateField(input_formats=['%Y-%m-%d'],required=True, widget=forms.SelectDateWidget(), initial=date.today())    
    #views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    #likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Messages
        fields = ('date',) 
        widgets = {'date': forms.DateInput(format='%Y-%m-%d', attrs={'class': 'datepicker'})}
        

blog/monitor/views.py
from django.http import HttpResponse
from django.shortcuts import render
import collections
import re
from .models import Messages
from django.template import loader
from calendar import monthrange
from datetime import datetime, date, timedelta
from django.shortcuts import render
from django.http import HttpResponse
from django.template import Context
from django.http import HttpResponseRedirect
from .forms import DateRangeForm
from django.template import RequestContext
from .funcs import pid_number
from time import time
from django.db.models import Count

def about(request):
    if request.method=='GET':
        date_report = request.GET.get('date')    
    #latest_question_list = Messages.objects.order_by('time')[:14]
    #c = Messages.objects.count()
    #output = ', '.join([str(q.date) for q in latest_question_list])    
    #return HttpResponse(output + ' '+ str(c))
    pid_d = {}
    template = loader.get_template('monitor/about.html')    
    latest_question_list = Messages.objects.filter(date=date_report) 
    number_messages = Messages.objects.filter(channel_name='').count()
    #output = ', '.join([str(q.date) for q in latest_question_list])      
    context = {
        'latest_question_list':  latest_question_list,
        'number': number_messages,      
    }        
    return HttpResponse(template.render(context, request))
    
def details(request):
    date_today = datetime.today()
    no_messages_channels = 0
    template = loader.get_template('monitor/details.html')   
    time_24_hours_ago = datetime.now() - timedelta(days=1)
    s = Messages.objects.values('channel_name').distinct().count()
    no_messages_channels = s - Messages.objects.values('channel_name').exclude(message='').distinct().count()
    latest_message = Messages.objects.values('channel_name').distinct().filter(date=date.today().strftime('%Y-%m-%d')).count()#(time__gte=time_24_hours_ago)   
    context = {
        's' :  s,
        'date_report': date_today, 
        'no_messages_channels' : no_messages_channels,
        'number_with_messages_24h': latest_message,
        'number_without_messages_24h' : s - latest_message,
    }          
    return HttpResponse(template.render(context, request))


def index(request):
    latest_question_list = Messages.objects.order_by('time')[:10]
    template = loader.get_template('monitor/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    form = DateRangeForm()    
    return HttpResponse(template.render(context, request))

 
def datepickerview(request):
    pid_d = {}
    template = loader.get_template('monitor/datepickerview.html') 
    # A HTTP POST?
    if request.method == 'POST':
        form = DateRangeForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            #mydate = form.cleaned_data('date')
            #s.filter(uploaded_time__year=selected_date.year,
            #                             uploaded_time__month=selected_date.month)  
            date_report  = request.POST['date']
            pid_d, context = pid_number(pid_d, date_report)    
            return HttpResponse(template.render(context, request))
        else:
            # The supplied form contained errors - just print them to the terminal.
            print (form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        date_report  = date.today().strftime('%Y-%m-%d')
        pid_d, context = pid_number(pid_d, date_report)
    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    #context = RequestContext(request)
    return HttpResponse(template.render(context, request))

blog/monitor/templates/monitor/about.html
  <!doctype html>
 <html lang="en">
<head>
 <a href="/monitor/datepickerview/">Назад</a>
{% if latest_question_list %}
     <table border = "3">
    <tr>
      <th>Название канала</th>
      <th>ID канала </th>
      <th>ID поста </th>
      <th>Дата поста </th>
      <th>Время поста </th>
      <th>Ссылка на него </th>
      <th>Количество просмотров</th>
      <th>Дата закачки </th>
      <th>Время закачки </th>     
      <th>ID Процесса/Поток </th>
      <th>Текст сообщения </th>
      <th> </th>
    </tr>
    {% for q in latest_question_list %} 
      <tr>
        <td>{{ q.channel_name }}</td>
        <td>{{ q.channel_id }}</td>
        <td>{{ q.message_id }}</td>
        <td>{{ q.date }}</td>
        <td>{{ q.time }}</td>
        <td>{{ q.url }}</td>
        <td>{{ q.views }}</td>
        <td>{{ q.date_added }}</td>
        <td>{{ q.time_added }}</td>
        <td>{{ q.pid_thread }}</td>
        <td>{{ q.message }}</td> 
          {% endfor %}


{% else %}
    <p>No messages are available.</p>
{% endif %}
</head>
</html>

blog/monitor/templates/monitor/datepickerview.html
  <!doctype html>
        {% load staticfiles %}
 <link rel="stylesheet" type="text/css" href="{% static 'monitor/datepickerview.css' %}" />
 <html lang="en">
<head>
 <h3><a href="/monitor/">Назад</a></h3>
<h3><a href="/monitor/details/">Общая статистика<h2 style="font-family:tempus sans itc;"></h2></a></h3>
<p> За {{date_report}}: </p>
{% if latest_question_list %}
  <table align = "center", border = "1">
    <tr>
      <th>ID Процесса/Поток</th>
      <th> <a href="/monitor/about/?date={{date_report}}">Собрано </a></th>
    </tr>
    {% for obj_pid, obj_n in pid_d %} 
      <tr>
        <td>{{ obj_pid }}</td>
        <td align="center">{{ obj_n }}</td>



      </tr>   
    {% endfor %}
           <tfoot>
            <tr>
        <td align="center">Всего</td>
        <td align="center">{{sum_obj}}</td>
            </tr>
         </tfoot>
  </table>
{% else %}
    <p>No messages are available.</p>
{% endif %}


        <meta charset="utf-8" />
        <title>Form</title>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />
        <script>
        $(function() {

            $( "#id_date" ).datepicker({ dateFormat: "yy-mm-dd" });
        });
        </script>
    </head>
    <body>
        <form action="/monitor/datepickerview/" method="post">{% csrf_token %}
            <!--{{ form.date }} -->
            <p>Дата: <input name='date' type="text" id="id_date"></p>
            <!-- The rest of my form -->
            <input type="submit" value="Поиск" />
        </form>
    </body>
</html>

blog/monitor/templates/monitor/details.html
  <!doctype html>
 <html lang="en">
         {% load staticfiles %}

     <link rel="stylesheet" type="text/css" href="{% static 'monitor/details.css' %}" />
<head>
	<body>
	 <h3><p><a href="/monitor/">Назад</a></p></h3>
	 <h3><a href="/monitor/datepickerview/">Отчет по дням</a></h3>
	 <h3><p> Отчет на {{date_report}}: </p></h3>
	 <pre>

     </pre>
	   <table align = "center">
    <tr>
    <th>Количество каналов:</th>
    <th>{{s}} </th>
    </tr>
    <tr>
      <th> Количество каналов без сообщений:</th>
    <th>{{ no_messages_channels }} </th>  
</tr>
    <tr>
      <th> Каналов обновлено за последние сутки:</th>
    <th>{{number_with_messages_24h}} </th>  
</tr>
</tr>
    <tr>
      <th> Каналов без обновлений за последние сутки:</th>
    <th> {{number_without_messages_24h}} </th>  
</tr>

      </table>
</body>
</html>

blog/monitor/templates/monitor/forms.html
<!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Form</title>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css" />
        <script>
        $(function() {
        $( "#id_date" ).datepicker();
        });
        </script>
    </head>
    <body>
        <form action="/datepickerview/" method="post">{% csrf_token %}
            <!--{{ form.date }} -->
            <p>Date: <input name='date' type="text" id="id_date"></p>
            <!-- The rest of my form -->
            <input type="submit" value="login" />
        </form>
    </body>

blog/monitor/templates/monitor/index.html
    <!doctype html>
        {% load staticfiles %}

    
    <html lang="en">
    <head>
   <link rel="stylesheet" type="text/css" href="{% static 'monitor/monitor.css' %}" />
                  </head>
             <body> 
              <h1> Monitor app </h1>
       <h3> <a href="/monitor/datepickerview/">Отчет по дням</a></h3>
        <h2 style="font-family:tempus sans itc;"></h2></a>
        <h3><a href="/monitor/details/">Общая статистика<h2 style="font-family:tempus sans itc;"></h2></a></h3>
        <img src="{% static "/monitor/monitor.jpg" %}" allign = center />

    </body>
</html>

blog/monitor/templates/monitor/table_search.html
<div class="container">
  <form action="/InterfaceApp/home/" method="post" class="form">
  {% csrf_token %}
    <div class="daterangepicker-container mcast-search-filter">
        <div class="daterangepicker-label">Date range:</div>
        <div id="daterange" class="daterangepicker-content">
            {% load bootstrap %}
            {% bootstrap_form daterange_form %}
            <i class="icon-calendar icon-large"></i>
        </div>
    </div>
  </form>
</div>
<script>
    // the start_date and end_date are the ids that django form fields created
    $("#daterange").daterangepicker({
        locale: {
          format: 'YYYY-MM-DD'
        },
        startDate: '{{daterange_form.start_date.value}}',
        endDate: '{{daterange_form.end_date.value}}'
    });
</script>

blog/monitor/templates/monitor/test.html
{% extends "base.html" %}

{% block content %}
    {% if info %}
        <pre>{{ info }}</pre>
    {% else %}

        <form action="" method="post">
        {{ form.as_p }}
        <p><input type="submit" value="go"/></p>
        </form>
    {% endif %}
{% endblock %}